/* eslint-disable no-console */
require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const Employee = require('../models/Employee');
const Task = require('../models/Task');
const PerformanceRecord = require('../models/PerformanceRecord');
const Alert = require('../models/Alert');
const AppSettings = require('../models/AppSettings');

function risk(level, score) {
  return { level, score, lastUpdated: new Date('2026-03-01') };
}

async function run() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('Set MONGODB_URI in server/.env');
    process.exit(1);
  }
  await mongoose.connect(uri);

  await Promise.all([
    User.deleteMany({}),
    Employee.deleteMany({}),
    Task.deleteMany({}),
    PerformanceRecord.deleteMany({}),
    Alert.deleteMany({}),
    AppSettings.deleteMany({}),
  ]);

  const hash = (p) => bcrypt.hash(p, 10);

  const adminUser = await User.create({
    name: 'Priya Sharma',
    email: 'admin@ems.demo',
    password: await hash('Admin12345'),
    role: 'admin',
  });

  const managerUser = await User.create({
    name: 'Rahul Verma',
    email: 'manager@ems.demo',
    password: await hash('Manager12345'),
    role: 'manager',
  });

  const PORTAL_EMPLOYEES = 8;
  const empUsers = [];
  for (let i = 0; i < PORTAL_EMPLOYEES; i += 1) {
    empUsers.push(
      await User.create({
        name: `Employee User ${i + 1}`,
        email: `employee${i + 1}@ems.demo`,
        password: await hash('Employee12345'),
        role: 'employee',
      })
    );
  }

  await AppSettings.create({
    key: 'global',
    performanceWeights: { w1: 0.25, w2: 0.35, w3: 0.25, w4: 0.15 },
  });

  const employeesData = [
    {
      userId: empUsers[0]._id,
      fullName: 'Ananya Iyer',
      email: 'ananya.iyer@company.demo',
      department: 'Engineering',
      designation: 'Senior Developer',
      skills: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'System design', 'Security'],
      experienceYears: 5,
      salary: 115000,
      joiningDate: new Date('2020-03-15'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 72,
      attendanceRate: 94,
      taskCompletionRate: 88,
      deadlineAdherenceRate: 90,
      peerFeedbackScore: 86,
      engagementScore: 78,
      lastPromotionDate: new Date('2023-01-10'),
      attritionRisk: risk('Low', 22),
      performanceHistory: [
        { date: new Date('2025-10-01'), weightedScore: 82, remarks: 'Strong sprint' },
        { date: new Date('2025-11-01'), weightedScore: 84, remarks: 'Strong delivery' },
        { date: new Date('2025-12-01'), weightedScore: 86, remarks: 'Stable' },
        { date: new Date('2026-01-01'), weightedScore: 87, remarks: 'Improving' },
      ],
    },
    {
      userId: empUsers[1]._id,
      fullName: 'Vikram Singh',
      email: 'vikram.singh@company.demo',
      department: 'Engineering',
      designation: 'Developer',
      skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Security'],
      experienceYears: 3,
      salary: 78000,
      joiningDate: new Date('2022-07-01'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 91,
      attendanceRate: 66,
      taskCompletionRate: 70,
      deadlineAdherenceRate: 63,
      peerFeedbackScore: 68,
      engagementScore: 38,
      lastPromotionDate: new Date('2022-07-01'),
      attritionRisk: risk('High', 78),
      performanceHistory: [
        { date: new Date('2025-10-01'), weightedScore: 78, remarks: 'Baseline' },
        { date: new Date('2025-11-01'), weightedScore: 76, remarks: 'Okay' },
        { date: new Date('2025-12-01'), weightedScore: 71, remarks: 'Slip' },
        { date: new Date('2026-01-01'), weightedScore: 66, remarks: 'Needs support' },
      ],
    },
    {
      userId: empUsers[2]._id,
      fullName: 'Neha Kapoor',
      email: 'neha.kapoor@company.demo',
      department: 'Product',
      designation: 'Product Analyst',
      skills: ['SQL', 'Analytics', 'Figma', 'Roadmapping', 'Communication'],
      experienceYears: 4,
      salary: 82000,
      joiningDate: new Date('2021-05-20'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 55,
      attendanceRate: 91,
      taskCompletionRate: 85,
      deadlineAdherenceRate: 88,
      peerFeedbackScore: 92,
      engagementScore: 80,
      lastPromotionDate: new Date('2024-06-01'),
      attritionRisk: risk('Low', 18),
      performanceHistory: [
        { date: new Date('2025-10-01'), weightedScore: 86, remarks: 'Solid' },
        { date: new Date('2025-11-01'), weightedScore: 88, remarks: 'Excellent stakeholder mgmt' },
        { date: new Date('2025-12-01'), weightedScore: 89, remarks: 'Consistent' },
        { date: new Date('2026-01-01'), weightedScore: 90, remarks: 'Leadership signal' },
      ],
    },
    {
      userId: empUsers[3]._id,
      fullName: 'Arjun Mehta',
      email: 'arjun.mehta@company.demo',
      department: 'Engineering',
      designation: 'QA Engineer',
      skills: ['Testing', 'Cypress', 'API testing', 'JavaScript', 'Docker'],
      experienceYears: 2,
      salary: 52000,
      joiningDate: new Date('2023-11-01'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 58,
      attendanceRate: 89,
      taskCompletionRate: 82,
      deadlineAdherenceRate: 84,
      peerFeedbackScore: 80,
      engagementScore: 70,
      lastPromotionDate: new Date('2023-11-01'),
      attritionRisk: risk('Low', 25),
      performanceHistory: [
        { date: new Date('2025-11-01'), weightedScore: 78, remarks: 'Growing' },
        { date: new Date('2026-01-01'), weightedScore: 80, remarks: 'Reliable' },
      ],
    },
    {
      userId: empUsers[4]._id,
      fullName: 'Kavya Nair',
      email: 'kavya.nair@company.demo',
      department: 'HR',
      designation: 'HR Specialist',
      skills: ['Recruiting', 'Policy', 'Communication', 'Compliance'],
      experienceYears: 6,
      salary: 68000,
      joiningDate: new Date('2019-02-01'),
      reportingManager: 'Priya Sharma',
      currentWorkload: 68,
      attendanceRate: 96,
      taskCompletionRate: 90,
      deadlineAdherenceRate: 92,
      peerFeedbackScore: 88,
      engagementScore: 85,
      lastPromotionDate: new Date('2021-03-01'),
      attritionRisk: risk('Low', 15),
      performanceHistory: [
        { date: new Date('2025-09-01'), weightedScore: 89, remarks: 'HR ops' },
        { date: new Date('2026-01-01'), weightedScore: 91, remarks: 'Top HR ops' },
      ],
    },
    {
      userId: empUsers[5]._id,
      fullName: 'Siddharth Rao',
      email: 'siddharth.rao@company.demo',
      department: 'Engineering',
      designation: 'DevOps Engineer',
      skills: ['Kubernetes', 'AWS', 'CI/CD', 'Terraform', 'Docker', 'Monitoring'],
      experienceYears: 4,
      salary: 95000,
      joiningDate: new Date('2021-09-10'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 62,
      attendanceRate: 93,
      taskCompletionRate: 91,
      deadlineAdherenceRate: 89,
      peerFeedbackScore: 84,
      engagementScore: 76,
      lastPromotionDate: new Date('2023-04-01'),
      attritionRisk: risk('Low', 20),
      performanceHistory: [
        { date: new Date('2025-12-01'), weightedScore: 88, remarks: 'SRE wins' },
        { date: new Date('2026-01-01'), weightedScore: 89, remarks: 'Infra champion' },
      ],
    },
    {
      userId: empUsers[6]._id,
      fullName: 'Meera Joshi',
      email: 'meera.joshi@company.demo',
      department: 'Design',
      designation: 'UX Designer',
      skills: ['Figma', 'Research', 'Prototyping', 'Accessibility', 'Design systems'],
      experienceYears: 3,
      salary: 72000,
      joiningDate: new Date('2022-04-18'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 58,
      attendanceRate: 90,
      taskCompletionRate: 86,
      deadlineAdherenceRate: 87,
      peerFeedbackScore: 90,
      engagementScore: 82,
      lastPromotionDate: new Date('2022-04-18'),
      attritionRisk: risk('Low', 19),
      performanceHistory: [
        { date: new Date('2025-11-01'), weightedScore: 86, remarks: 'Research depth' },
        { date: new Date('2026-01-01'), weightedScore: 88, remarks: 'Great craft' },
      ],
    },
    {
      userId: empUsers[7]._id,
      fullName: 'Rohan Desai',
      email: 'rohan.desai@company.demo',
      department: 'Engineering',
      designation: 'Backend Engineer',
      skills: ['Node.js', 'MongoDB', 'PostgreSQL', 'REST APIs', 'JavaScript'],
      experienceYears: 4,
      salary: 88000,
      joiningDate: new Date('2021-11-08'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 64,
      attendanceRate: 92,
      taskCompletionRate: 87,
      deadlineAdherenceRate: 85,
      peerFeedbackScore: 82,
      engagementScore: 74,
      lastPromotionDate: new Date('2024-02-01'),
      attritionRisk: risk('Medium', 44),
      performanceHistory: [
        { date: new Date('2025-10-01'), weightedScore: 83, remarks: 'API quality' },
        { date: new Date('2025-12-01'), weightedScore: 85, remarks: 'Reliable' },
        { date: new Date('2026-01-01'), weightedScore: 86, remarks: 'Steady' },
      ],
    },
    {
      fullName: 'Pooja Reddy',
      email: 'pooja.reddy@company.demo',
      department: 'Data',
      designation: 'Data Analyst',
      skills: ['SQL', 'Python', 'Analytics', 'Tableau', 'ETL'],
      experienceYears: 3,
      salary: 76000,
      joiningDate: new Date('2022-08-22'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 52,
      attendanceRate: 93,
      taskCompletionRate: 88,
      deadlineAdherenceRate: 86,
      peerFeedbackScore: 85,
      engagementScore: 77,
      lastPromotionDate: new Date('2022-08-22'),
      attritionRisk: risk('Low', 21),
      performanceHistory: [
        { date: new Date('2025-12-01'), weightedScore: 87, remarks: 'Dashboards' },
        { date: new Date('2026-01-01'), weightedScore: 88, remarks: 'Insightful' },
      ],
    },
    {
      fullName: 'Amit Khanna',
      email: 'amit.khanna@company.demo',
      department: 'Engineering',
      designation: 'Tech Lead',
      skills: ['System design', 'JavaScript', 'Node.js', 'Mentoring', 'Architecture'],
      experienceYears: 8,
      salary: 132000,
      joiningDate: new Date('2018-04-02'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 70,
      attendanceRate: 95,
      taskCompletionRate: 92,
      deadlineAdherenceRate: 91,
      peerFeedbackScore: 91,
      engagementScore: 88,
      lastPromotionDate: new Date('2024-09-01'),
      attritionRisk: risk('Low', 16),
      performanceHistory: [
        { date: new Date('2025-11-01'), weightedScore: 90, remarks: 'Leadership' },
        { date: new Date('2026-01-01'), weightedScore: 91, remarks: 'Team multiplier' },
      ],
    },
    {
      fullName: 'Sanjana Pillai',
      email: 'sanjana.pillai@company.demo',
      department: 'Design',
      designation: 'UI Designer',
      skills: ['Figma', 'Prototyping', 'Accessibility', 'Illustration'],
      experienceYears: 2,
      salary: 58000,
      joiningDate: new Date('2023-06-12'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 49,
      attendanceRate: 88,
      taskCompletionRate: 84,
      deadlineAdherenceRate: 83,
      peerFeedbackScore: 86,
      engagementScore: 72,
      lastPromotionDate: new Date('2023-06-12'),
      attritionRisk: risk('Low', 28),
      performanceHistory: [{ date: new Date('2026-01-01'), weightedScore: 83, remarks: 'Visual polish' }],
    },
    {
      fullName: 'Karthik Menon',
      email: 'karthik.menon@company.demo',
      department: 'Product',
      designation: 'Product Manager',
      skills: ['Roadmapping', 'Analytics', 'Communication', 'Stakeholder management'],
      experienceYears: 6,
      salary: 105000,
      joiningDate: new Date('2019-09-16'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 74,
      attendanceRate: 90,
      taskCompletionRate: 89,
      deadlineAdherenceRate: 88,
      peerFeedbackScore: 88,
      engagementScore: 81,
      lastPromotionDate: new Date('2023-03-01'),
      attritionRisk: risk('Medium', 41),
      performanceHistory: [
        { date: new Date('2025-11-01'), weightedScore: 87, remarks: 'Ship velocity' },
        { date: new Date('2026-01-01'), weightedScore: 88, remarks: 'Prioritization' },
      ],
    },
    {
      fullName: 'Divya Raman',
      email: 'divya.raman@company.demo',
      department: 'HR',
      designation: 'Talent Acquisition',
      skills: ['Recruiting', 'Sourcing', 'Communication', 'Policy'],
      experienceYears: 4,
      salary: 62000,
      joiningDate: new Date('2021-07-19'),
      reportingManager: 'Priya Sharma',
      currentWorkload: 61,
      attendanceRate: 94,
      taskCompletionRate: 87,
      deadlineAdherenceRate: 89,
      peerFeedbackScore: 84,
      engagementScore: 79,
      lastPromotionDate: new Date('2023-11-01'),
      attritionRisk: risk('Low', 23),
      performanceHistory: [{ date: new Date('2026-01-01'), weightedScore: 87, remarks: 'Pipeline health' }],
    },
    {
      fullName: 'Naveen Krishnan',
      email: 'naveen.krishnan@company.demo',
      department: 'Engineering',
      designation: 'Mobile Developer',
      skills: ['React Native', 'JavaScript', 'TypeScript', 'REST APIs', 'Testing'],
      experienceYears: 3,
      salary: 84000,
      joiningDate: new Date('2022-03-07'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 66,
      attendanceRate: 91,
      taskCompletionRate: 86,
      deadlineAdherenceRate: 84,
      peerFeedbackScore: 83,
      engagementScore: 75,
      lastPromotionDate: new Date('2024-01-15'),
      attritionRisk: risk('Low', 24),
      performanceHistory: [
        { date: new Date('2025-12-01'), weightedScore: 85, remarks: 'Mobile stability' },
        { date: new Date('2026-01-01'), weightedScore: 86, remarks: 'Release quality' },
      ],
    },
    {
      fullName: 'Lakshmi Venkat',
      email: 'lakshmi.venkat@company.demo',
      department: 'Finance',
      designation: 'Financial Analyst',
      skills: ['Excel', 'SQL', 'Reporting', 'Compliance', 'Communication'],
      experienceYears: 5,
      salary: 72000,
      joiningDate: new Date('2020-11-23'),
      reportingManager: 'Priya Sharma',
      currentWorkload: 56,
      attendanceRate: 97,
      taskCompletionRate: 91,
      deadlineAdherenceRate: 93,
      peerFeedbackScore: 86,
      engagementScore: 80,
      lastPromotionDate: new Date('2022-08-01'),
      attritionRisk: risk('Low', 17),
      performanceHistory: [{ date: new Date('2026-01-01'), weightedScore: 90, remarks: 'Forecast accuracy' }],
    },
    {
      fullName: 'Esha Malhotra',
      email: 'esha.malhotra@company.demo',
      department: 'Engineering',
      designation: 'Junior Developer',
      skills: ['JavaScript', 'React', 'Git', 'Testing'],
      experienceYears: 1,
      salary: 48000,
      joiningDate: new Date('2025-01-15'),
      reportingManager: 'Amit Khanna',
      currentWorkload: 45,
      attendanceRate: 92,
      taskCompletionRate: 78,
      deadlineAdherenceRate: 76,
      peerFeedbackScore: 81,
      engagementScore: 68,
      lastPromotionDate: new Date('2025-01-15'),
      attritionRisk: risk('Low', 30),
      performanceHistory: [{ date: new Date('2026-01-01'), weightedScore: 79, remarks: 'Learning curve' }],
    },
    {
      fullName: 'Aditya Bose',
      email: 'aditya.bose@company.demo',
      department: 'Customer Success',
      designation: 'CSM',
      skills: ['Communication', 'CRM', 'Analytics', 'Training'],
      experienceYears: 4,
      salary: 64000,
      joiningDate: new Date('2021-04-05'),
      reportingManager: 'Priya Sharma',
      currentWorkload: 59,
      attendanceRate: 90,
      taskCompletionRate: 88,
      deadlineAdherenceRate: 87,
      peerFeedbackScore: 89,
      engagementScore: 83,
      lastPromotionDate: new Date('2023-05-01'),
      attritionRisk: risk('Low', 22),
      performanceHistory: [{ date: new Date('2026-01-01'), weightedScore: 87, remarks: 'NPS lift' }],
    },
    {
      fullName: 'Ritu Saxena',
      email: 'ritu.saxena@company.demo',
      department: 'Data',
      designation: 'ML Engineer',
      skills: ['Python', 'TensorFlow', 'MLOps', 'Docker', 'SQL'],
      experienceYears: 4,
      salary: 102000,
      joiningDate: new Date('2021-10-11'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 71,
      attendanceRate: 92,
      taskCompletionRate: 89,
      deadlineAdherenceRate: 87,
      peerFeedbackScore: 87,
      engagementScore: 78,
      lastPromotionDate: new Date('2024-04-01'),
      attritionRisk: risk('Low', 26),
      performanceHistory: [
        { date: new Date('2025-11-01'), weightedScore: 88, remarks: 'Model quality' },
        { date: new Date('2026-01-01'), weightedScore: 89, remarks: 'Pipeline robustness' },
      ],
    },
    {
      fullName: 'Manish Patil',
      email: 'manish.patil@company.demo',
      department: 'Engineering',
      designation: 'Site Reliability Engineer',
      skills: ['Kubernetes', 'Monitoring', 'AWS', 'CI/CD', 'Python'],
      experienceYears: 5,
      salary: 98000,
      joiningDate: new Date('2020-07-20'),
      reportingManager: 'Siddharth Rao',
      currentWorkload: 69,
      attendanceRate: 91,
      taskCompletionRate: 90,
      deadlineAdherenceRate: 88,
      peerFeedbackScore: 85,
      engagementScore: 77,
      lastPromotionDate: new Date('2023-06-01'),
      attritionRisk: risk('Low', 20),
      performanceHistory: [{ date: new Date('2026-01-01'), weightedScore: 88, remarks: 'Uptime' }],
    },
    {
      fullName: 'Tanvi Shah',
      email: 'tanvi.shah@company.demo',
      department: 'Product',
      designation: 'Associate PM',
      skills: ['Roadmapping', 'SQL', 'Figma', 'Communication'],
      experienceYears: 2,
      salary: 58000,
      joiningDate: new Date('2023-09-01'),
      reportingManager: 'Karthik Menon',
      currentWorkload: 54,
      attendanceRate: 89,
      taskCompletionRate: 83,
      deadlineAdherenceRate: 82,
      peerFeedbackScore: 84,
      engagementScore: 71,
      lastPromotionDate: new Date('2023-09-01'),
      attritionRisk: risk('Medium', 39),
      performanceHistory: [{ date: new Date('2026-01-01'), weightedScore: 82, remarks: 'Spec clarity' }],
    },
    {
      fullName: 'Ishan Choudhury',
      email: 'ishan.choudhury@company.demo',
      department: 'Engineering',
      designation: 'Full-stack Developer',
      skills: ['React', 'Node.js', 'MongoDB', 'TypeScript', 'Testing'],
      experienceYears: 3,
      salary: 79000,
      joiningDate: new Date('2022-05-30'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 63,
      attendanceRate: 87,
      taskCompletionRate: 85,
      deadlineAdherenceRate: 84,
      peerFeedbackScore: 82,
      engagementScore: 73,
      lastPromotionDate: new Date('2022-05-30'),
      attritionRisk: risk('Medium', 46),
      performanceHistory: [
        { date: new Date('2025-11-01'), weightedScore: 82, remarks: 'Feature delivery' },
        { date: new Date('2026-01-01'), weightedScore: 83, remarks: 'Consistent' },
      ],
    },
    {
      fullName: 'Deepa Varma',
      email: 'deepa.varma@company.demo',
      department: 'Engineering',
      designation: 'Security Engineer',
      skills: ['Security', 'Node.js', 'Penetration testing', 'Compliance', 'AWS'],
      experienceYears: 6,
      salary: 118000,
      joiningDate: new Date('2019-11-04'),
      reportingManager: 'Rahul Verma',
      currentWorkload: 60,
      attendanceRate: 94,
      taskCompletionRate: 90,
      deadlineAdherenceRate: 91,
      peerFeedbackScore: 88,
      engagementScore: 82,
      lastPromotionDate: new Date('2024-01-01'),
      attritionRisk: risk('Low', 19),
      performanceHistory: [{ date: new Date('2026-01-01'), weightedScore: 90, remarks: 'Security posture' }],
    },
  ];

  const employees = await Employee.insertMany(employeesData);
  const byName = (n) => employees.find((e) => e.fullName === n);

  const tasks = await Task.insertMany([
    {
      title: 'Migrate auth service to JWT cookies',
      description: 'Harden session handling, document flows, and rollout plan.',
      requiredSkills: ['Node.js', 'Security', 'MongoDB'],
      priority: 'high',
      deadline: new Date('2026-05-01'),
      status: 'in-progress',
      estimatedHours: 40,
      createdBy: managerUser._id,
      assignedTo: byName('Ananya Iyer')._id,
    },
    {
      title: 'Build attrition dashboard widgets',
      description: 'Charts for risk bands, workload, and drill-down by department.',
      requiredSkills: ['React', 'JavaScript', 'Analytics'],
      priority: 'medium',
      deadline: new Date('2026-04-20'),
      status: 'pending',
      estimatedHours: 24,
      createdBy: adminUser._id,
    },
    {
      title: 'API load testing for task allocation',
      description: 'k6 scripts, thresholds, and summary report for stakeholders.',
      requiredSkills: ['Testing', 'API testing', 'Docker'],
      priority: 'medium',
      deadline: new Date('2026-04-28'),
      status: 'assigned',
      estimatedHours: 16,
      createdBy: managerUser._id,
      assignedTo: byName('Arjun Mehta')._id,
    },
    {
      title: 'Policy handbook refresh',
      description: 'Update remote-work and data-handling chapters for 2026.',
      requiredSkills: ['Policy', 'Communication'],
      priority: 'low',
      deadline: new Date('2026-06-01'),
      status: 'in-progress',
      estimatedHours: 12,
      createdBy: adminUser._id,
      assignedTo: byName('Kavya Nair')._id,
    },
    {
      title: 'Design system tokens for InsightHR',
      description: 'Align colors, spacing, and dark mode with ShadCN-style tokens.',
      requiredSkills: ['Figma', 'Accessibility', 'Prototyping'],
      priority: 'high',
      deadline: new Date('2026-04-15'),
      status: 'pending',
      estimatedHours: 20,
      createdBy: managerUser._id,
    },
    {
      title: 'Customer churn analysis dashboard',
      description: 'SQL models + executive summary views in analytics tool.',
      requiredSkills: ['SQL', 'Analytics', 'Tableau'],
      priority: 'high',
      deadline: new Date('2026-04-25'),
      status: 'assigned',
      estimatedHours: 32,
      createdBy: managerUser._id,
      assignedTo: byName('Pooja Reddy')._id,
    },
    {
      title: 'Mobile app biometric authentication',
      description: 'Implement and test biometric login flow on iOS/Android.',
      requiredSkills: ['React Native', 'TypeScript', 'Testing'],
      priority: 'high',
      deadline: new Date('2026-05-10'),
      status: 'in-progress',
      estimatedHours: 48,
      createdBy: managerUser._id,
      assignedTo: byName('Naveen Krishnan')._id,
    },
    {
      title: 'Quarterly compliance audit checklist',
      description: 'Cross-functional checklist and evidence collection workflow.',
      requiredSkills: ['Compliance', 'Policy', 'Communication'],
      priority: 'medium',
      deadline: new Date('2026-04-30'),
      status: 'assigned',
      estimatedHours: 18,
      createdBy: adminUser._id,
      assignedTo: byName('Kavya Nair')._id,
    },
    {
      title: 'Sales CRM integration API',
      description: 'Bidirectional sync for accounts and opportunities.',
      requiredSkills: ['Node.js', 'REST APIs', 'PostgreSQL'],
      priority: 'medium',
      deadline: new Date('2026-05-18'),
      status: 'assigned',
      estimatedHours: 36,
      createdBy: managerUser._id,
      assignedTo: byName('Rohan Desai')._id,
    },
    {
      title: 'Data pipeline monitoring and alerts',
      description: 'Alerting rules for ETL failures and latency SLOs.',
      requiredSkills: ['Python', 'Monitoring', 'Docker', 'SQL'],
      priority: 'high',
      deadline: new Date('2026-04-22'),
      status: 'in-progress',
      estimatedHours: 28,
      createdBy: managerUser._id,
      assignedTo: byName('Manish Patil')._id,
    },
    {
      title: 'Onboarding flow UX research',
      description: 'Interviews, journey map, and recommendations deck.',
      requiredSkills: ['Research', 'Figma', 'Communication'],
      priority: 'medium',
      deadline: new Date('2026-05-05'),
      status: 'assigned',
      estimatedHours: 22,
      createdBy: managerUser._id,
      assignedTo: byName('Meera Joshi')._id,
    },
    {
      title: 'Product roadmap Q3 workshop',
      description: 'Facilitate prioritization workshop and publish outcomes.',
      requiredSkills: ['Roadmapping', 'Stakeholder management', 'Communication'],
      priority: 'medium',
      deadline: new Date('2026-04-18'),
      status: 'in-progress',
      estimatedHours: 14,
      createdBy: adminUser._id,
      assignedTo: byName('Karthik Menon')._id,
    },
    {
      title: 'Technical debt backlog grooming',
      description: 'Triage top 30 items with effort/risk scoring.',
      requiredSkills: ['Architecture', 'System design', 'Communication'],
      priority: 'low',
      deadline: new Date('2026-05-28'),
      status: 'assigned',
      estimatedHours: 10,
      createdBy: managerUser._id,
      assignedTo: byName('Amit Khanna')._id,
    },
    {
      title: 'Intern mentorship program documentation',
      description: 'Playbook, milestones, and evaluation rubric.',
      requiredSkills: ['Mentoring', 'Communication', 'Git'],
      priority: 'low',
      deadline: new Date('2026-06-10'),
      status: 'in-progress',
      estimatedHours: 12,
      createdBy: managerUser._id,
      assignedTo: byName('Esha Malhotra')._id,
    },
    {
      title: 'ML model monitoring microservice',
      description: 'Drift detection hooks and dashboard integration.',
      requiredSkills: ['Python', 'MLOps', 'Docker', 'SQL'],
      priority: 'high',
      deadline: new Date('2026-05-22'),
      status: 'assigned',
      estimatedHours: 40,
      createdBy: managerUser._id,
      assignedTo: byName('Ritu Saxena')._id,
    },
    {
      title: 'Customer ticket triage bot specification',
      description: 'PRD, intents, and guardrails for support automation.',
      requiredSkills: ['Roadmapping', 'Analytics', 'Communication'],
      priority: 'medium',
      deadline: new Date('2026-04-26'),
      status: 'pending',
      estimatedHours: 16,
      createdBy: managerUser._id,
    },
    {
      title: 'Payroll system UAT cycle',
      description: 'Test cases, sign-off matrix, and defect log.',
      requiredSkills: ['Excel', 'Reporting', 'Compliance'],
      priority: 'high',
      deadline: new Date('2026-04-12'),
      status: 'in-progress',
      estimatedHours: 24,
      createdBy: adminUser._id,
      assignedTo: byName('Lakshmi Venkat')._id,
    },
    {
      title: 'AWS cost optimization review',
      description: 'Rightsizing report and savings recommendations.',
      requiredSkills: ['AWS', 'Kubernetes', 'Monitoring'],
      priority: 'medium',
      deadline: new Date('2026-05-15'),
      status: 'assigned',
      estimatedHours: 20,
      createdBy: adminUser._id,
      assignedTo: byName('Siddharth Rao')._id,
    },
    {
      title: 'Accessibility audit for employee portal',
      description: 'WCAG-oriented audit with remediation backlog.',
      requiredSkills: ['Accessibility', 'Figma', 'Testing'],
      priority: 'medium',
      deadline: new Date('2026-05-01'),
      status: 'pending',
      estimatedHours: 18,
      createdBy: managerUser._id,
    },
    {
      title: 'Security pen-test remediation batch 1',
      description: 'Address critical/high findings from external assessment.',
      requiredSkills: ['Security', 'Node.js', 'Compliance'],
      priority: 'high',
      deadline: new Date('2026-04-14'),
      status: 'in-progress',
      estimatedHours: 32,
      createdBy: adminUser._id,
      assignedTo: byName('Vikram Singh')._id,
    },
    {
      title: 'Vendor contract renewal tracker',
      description: 'Workflow for renewals, approvals, and notifications.',
      requiredSkills: ['Policy', 'Communication', 'Compliance'],
      priority: 'low',
      deadline: new Date('2026-06-20'),
      status: 'pending',
      estimatedHours: 14,
      createdBy: adminUser._id,
    },
    {
      title: 'Feature flag service rollout',
      description: 'Gradual rollout plan and kill-switch runbooks.',
      requiredSkills: ['Node.js', 'Kubernetes', 'CI/CD'],
      priority: 'medium',
      deadline: new Date('2026-05-08'),
      status: 'pending',
      estimatedHours: 26,
      createdBy: managerUser._id,
    },
    {
      title: 'Legacy monolith strangler diagram',
      description: 'Document target state and migration milestones.',
      requiredSkills: ['Architecture', 'System design', 'Documentation'],
      priority: 'low',
      deadline: new Date('2026-06-05'),
      status: 'completed',
      estimatedHours: 8,
      createdBy: managerUser._id,
      assignedTo: byName('Amit Khanna')._id,
    },
    {
      title: 'Customer health score prototype',
      description: 'Prototype metrics and validation with CS team.',
      requiredSkills: ['Analytics', 'SQL', 'CRM'],
      priority: 'medium',
      deadline: new Date('2026-03-28'),
      status: 'completed',
      estimatedHours: 20,
      createdBy: managerUser._id,
      assignedTo: byName('Aditya Bose')._id,
    },
    {
      title: 'Search relevance tuning sprint',
      description: 'A/B config and offline eval for catalog search.',
      requiredSkills: ['Python', 'Analytics', 'SQL'],
      priority: 'medium',
      deadline: new Date('2026-03-20'),
      status: 'completed',
      estimatedHours: 16,
      createdBy: managerUser._id,
      assignedTo: byName('Ishan Choudhury')._id,
    },
  ]);

  const perfSamples = [];
  const perfPeriodStarts = [
    new Date('2025-08-05'),
    new Date('2025-09-08'),
    new Date('2025-10-06'),
    new Date('2025-11-10'),
    new Date('2025-12-09'),
    new Date('2026-01-07'),
  ];
  for (const emp of employees) {
    perfPeriodStarts.forEach((periodStart, i) => {
      const jitter = (emp.fullName.length + i * 3) % 7;
      const attendanceScore = Math.min(100, Math.max(0, emp.attendanceRate - i * 2 + (jitter % 3)));
      const taskCompletionScore = Math.min(100, Math.max(0, emp.taskCompletionRate - i + (jitter % 2)));
      const deadlineAdherenceScore = Math.min(100, Math.max(0, emp.deadlineAdherenceRate - i + 1));
      const peerFeedbackScore = Math.min(100, Math.max(0, emp.peerFeedbackScore - i));
      const weightedScore = Math.min(
        100,
        Math.max(
          0,
          0.25 * attendanceScore +
            0.35 * taskCompletionScore +
            0.25 * deadlineAdherenceScore +
            0.15 * peerFeedbackScore +
            jitter * 0.5
        )
      );
      perfSamples.push({
        employeeId: emp._id,
        attendanceScore,
        taskCompletionScore,
        deadlineAdherenceScore,
        peerFeedbackScore,
        weightedScore: Math.round(weightedScore * 10) / 10,
        breakdown: {
          weights: { w1: 0.25, w2: 0.35, w3: 0.25, w4: 0.15 },
          contributions: {
            attendance: Math.round(0.25 * attendanceScore * 10) / 10,
            taskCompletion: Math.round(0.35 * taskCompletionScore * 10) / 10,
            deadlineAdherence: Math.round(0.25 * deadlineAdherenceScore * 10) / 10,
            peerFeedback: Math.round(0.15 * peerFeedbackScore * 10) / 10,
          },
          defaultsUsed: [],
          explanation: `Historical snapshot (${i + 1}/6) for ${emp.fullName} — seeded for trends and anomaly demos.`,
        },
        remarks: `Cycle ${i + 1} — demo data`,
        createdAt: periodStart,
      });
    });
  }
  await PerformanceRecord.insertMany(perfSamples);

  await Alert.insertMany([
    {
      employeeId: byName('Vikram Singh')._id,
      type: 'attrition',
      severity: 'high',
      message: 'Elevated attrition risk: workload and attendance stressors.',
      isRead: false,
    },
    {
      employeeId: byName('Ananya Iyer')._id,
      type: 'promotion',
      severity: 'low',
      message: 'Promotion readiness trending up — review calibration.',
      isRead: false,
    },
    {
      employeeId: byName('Vikram Singh')._id,
      type: 'performance-drop',
      severity: 'medium',
      message: 'Performance composite declined over last two periods.',
      isRead: true,
    },
    {
      employeeId: byName('Neha Kapoor')._id,
      type: 'anomaly',
      severity: 'low',
      message: 'Unusual spike in peer feedback vs task completion — verify data entry.',
      isRead: false,
    },
    {
      employeeId: byName('Rohan Desai')._id,
      type: 'attrition',
      severity: 'medium',
      message: 'Medium risk: salary band vs tenure — schedule retention conversation.',
      isRead: false,
    },
    {
      employeeId: byName('Amit Khanna')._id,
      type: 'promotion',
      severity: 'low',
      message: 'Strong leadership signals — consider succession planning.',
      isRead: false,
    },
    {
      employeeId: byName('Tanvi Shah')._id,
      type: 'performance-drop',
      severity: 'low',
      message: 'Deadline adherence dipped vs prior quarter — check capacity.',
      isRead: false,
    },
    {
      employeeId: byName('Ishan Choudhury')._id,
      type: 'attrition',
      severity: 'medium',
      message: 'Workload elevated with flat engagement score — monitor burnout.',
      isRead: true,
    },
    {
      employeeId: byName('Karthik Menon')._id,
      type: 'anomaly',
      severity: 'medium',
      message: 'Task completion volatility higher than team baseline.',
      isRead: false,
    },
    {
      employeeId: byName('Deepa Varma')._id,
      type: 'promotion',
      severity: 'low',
      message: 'Security impact consistent — eligible for senior track discussion.',
      isRead: false,
    },
    {
      employeeId: byName('Esha Malhotra')._id,
      type: 'performance-drop',
      severity: 'low',
      message: 'Junior ramp: ensure mentorship hours are protected.',
      isRead: false,
    },
    {
      employeeId: byName('Pooja Reddy')._id,
      type: 'anomaly',
      severity: 'low',
      message: 'Attendance perfect while workload spiked — validate reporting source.',
      isRead: true,
    },
    {
      employeeId: byName('Manish Patil')._id,
      type: 'attrition',
      severity: 'low',
      message: 'Low risk but on-call load elevated — review rotation fairness.',
      isRead: false,
    },
    {
      employeeId: byName('Sanjana Pillai')._id,
      type: 'promotion',
      severity: 'low',
      message: 'Design craft scores improving — consider mid-level path.',
      isRead: false,
    },
  ]);

  for (const emp of employees) {
    const last = await PerformanceRecord.findOne({ employeeId: emp._id }).sort({ createdAt: -1 });
    if (last) {
      emp.promotionScore = Math.round(last.weightedScore * 0.9);
      await emp.save();
    }
  }

  console.log('Seed complete.');
  console.log('22 employees, 25 tasks, 6 performance records per employee, 14 alerts.');
  console.log('Admin: admin@ems.demo / Admin12345');
  console.log('Manager: manager@ems.demo / Manager12345');
  console.log('Employee portals: employee1@ems.demo … employee8@ems.demo / Employee12345');
  console.log('  (linked to first 8 employees in seed order)');
  await mongoose.disconnect();
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
